name: Run SSIS via SQL Agent
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  run-ssis:
    runs-on: self-hosted
 
    steps:
      - name: Trigger SQL Server Agent Job
        shell: powershell
        run: |
          Import-Module SqlServer
 
          $server = "localhost\SQLSERVER2025"
          $job = "Run_Timesheet_ETL"
 
          Invoke-Sqlcmd -ServerInstance $server `
                        -Query "EXEC msdb.dbo.sp_start_job N'$job';"