name: Deploy Local SQL
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    #  ADD ENVIRONMENT CONTROL (TEST FIRST, THEN CHANGE TO PRODUCTION LATER)
    environment: test
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Install SQLCMD
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18
 
      - name: Show secret status (debug)
        run: |
          if [[ -n "${{ secrets.SQL_SERVER }}" ]]; then
            echo "Secret SQL_SERVER is configured"
          else
            echo "WARNING: SQL_SERVER is missing"
          fi
 
      - name: Execute SQL Script
        env:
          SERVER: ${{ secrets.SQL_SERVER }}
          USERNAME: ${{ secrets.DB_USER }}
          PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          /opt/mssql-tools18/bin/sqlcmd \
          -S "$SERVER" \
          -U "$USERNAME" \
          -P "$PASSWORD" \
          -d "Cloud-tunnel-KP" \
          -i database/init.sql \
          -C